# Generated by Django 3.2 on 2022-12-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20221220_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depts', to='app1.college'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='college',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='princi', to='app1.college'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studs', to='app1.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='app1.department'),
        ),
    ]
